export const TEXT = Object.freeze({
  title: "AI estimate",
  ai_estimate: "AI Estimate",
  privacy_police: "Privacy policy",
  terms_of_use: "Terms of use",
  welcome: "Welcome to AI estimate",
  elevate: "Elevate your business experience with AI",
  phone_number: "Phone number",
  log_in: "Log In",
  new_to_ai: "New to AI estimate?",
  sign_up: "Sign Up",
  phone_required: "Phone field is required",
  invalid_phone: "Invalid phone number",
  start: "Start",
  check_out_phone: "Check out your phone",
  we_have_sent_code: "We’ve sent a code to your phone number: ",
  did_not_get_code: "Didn’t get your code?",
  resend_code: "Resend code",
  wrong_code: "The code is not valid",
  tell_us: "Tell us about yourself",
  your_name: "Your name",
  enter_your_name: "Enter your name",
  your_role: "Your role",
  choose_role: "Choose your role",
  create_account: "Create account",
  by_clicking: "By clicking “Create account” you are accepting our",
  and: "and",
  you_are_all_set: "You are all set!",
  glad_to_see_you: "Glad to see you",
  start_journey: "Start your journey",
  project_name: "Project name",
  notes_to_ai: "Notes to AI",
  files: "Notes to AI",
  tell_us_about_project: "Tell us about your project",
  enter_project_name: "Enter project name",
  enter_notes_ai: "Enter notes to AI",
  choose_files: "Choose files",
  drag_and_drop: "Drag and drop your file or",
  drop_here: "Drop files here",
  text_files_limit: "Text files limit",
  img_files_limit: "Visual files limit",
  enter_file_desc: "Enter file description",
  submit: "Submit",
  add_new_files: "Add new files",
  estimating_process: "Estimating process...",
  analyze_files: "Analyze your files",
  copy: "Copy",
  link_is_ready: "Your link is ready!",
  link_was_copied: "Copied",
  go_to_your_file: "Go to your file",
});

export const ERRORS_TEXT = Object.freeze({
  send_code_error: "Code sending was failed",
  invalid_code: "Invalid code",
  submit_error: "Submit error",
  copy_error: "Link wasn't copied",
});
