export const TEXT = Object.freeze({
  title: "AI estimate",
  ai_estimate: "AI Estimate",
  privacy_police: "Privacy policy",
  terms_of_use: "Terms of use",
  welcome: "Welcome to AI estimate",
  elevate: "Elevate your business experience with AI",
  phone_number: "Phone number",
  log_in: "Log In",
  new_to_ai: "New to AI estimate?",
  sign_up: "Sign Up",
  phone_required: "Phone field is required",
  invalid_phone: "Invalid phone number",
  start: "Start",
  check_out_phone: "Check out your phone",
  we_have_sent_code: "We’ve sent a code to your phone number: ",
  did_not_get_code: "Didn’t get your code?",
  resend_code: "Resend code",
  wrong_code: "The code is not valid",
  tell_us: "Tell us about yourself",
  your_name: "Your name",
  enter_your_name: "Enter your name",
  your_role: "Your role",
  choose_role: "Choose your role",
  create_account: "Create account",
  by_clicking: "By clicking “Create account” you are accepting our",
  and: "and",
  you_are_all_set: "You are all set!",
  glad_to_see_you: "Glad to see you",
  start_journey: "Start your journey",
  project_name: "Project name",
  notes_to_ai: "Notes to AI",
  files: "Notes to AI",
  tell_us_about_project: "Tell us about your project",
  enter_project_name: "Enter project name",
  enter_notes_ai: "Enter notes to AI",
  choose_files: "Choose files",
  drag_and_drop: "Drag and drop your file or",
  drop_here: "Drop files here",
  text_files_limit: "Text files limit",
  img_files_limit: "Visual files limit",
  enter_file_desc: "Enter file description",
  submit: "Submit",
  add_new_files: "Add new files",
  estimating_process: "Estimating process...",
  analyze_files: "Analyze your files",
  copy: "Copy",
  link_is_ready: "Your link is ready!",
  link_was_copied: "Copied",
  go_to_your_file: "Go to your file",
  unlimited: "Unlimited",
  view_profile: "View profile",
  log_out: "Log out",
  personal_info: "Personal info",
  name: "Name",
  role: "Role",
  account: "Account",
  sign_out: "Sign out",
  delete_account: "Delete Account",
  edit: "Edit",
  cancel: "Cancel",
  save: "Save",
  profile_updated: "Profile was updated",
  change_phone: "Change your phone number",
  new_phone: "New phone number",
  get_code: "Get the code",
  code_sent_again: "Code send again",
  phone_changed_success: "Phone was changed",
  try_again: "Try again",
  yes: "Yes",
  no: "No",
  not_specified: "Not specified",
  we_wont_deduct: "We won’t deduct your attempt for this operation.",
});

export const ERRORS_TEXT = Object.freeze({
  send_code_error: "Code sending was failed",
  invalid_code: "Invalid code",
  submit_error: "Submit error",
  copy_error: "Link wasn't copied",
  stripe_error: "Payment error",
  user_delete_error: "User delete error",
  profile_update_error: "Profile update error",
  something_went_wrong: "😞 Oops! Something went wrong.",
  working_on_it:
    "We're already working to fix it. Please try again in a few moments.",
  restore_data_error: "Restore data was failed",
});

export const MODALS_TEXT = Object.freeze({
  free_limit: "Free limit reached",
  used_all: " You’ve used all",
  free_estimations: "free estimations.",
  upgrade_stripe: "Upgrade on Stripe",
  maybe_later: "Maybe later",
  are_you_sure: "Are you sure?",
  yes_delete: "Yes, delete",
  delete_account:
    "Deleting your account is permanent. You will no longer be able to create an account with this email.",
  restore_data: "Restore data",
  do_you_want_to_restore: "Do you want to restore previous information?",
  upgrade_plan: "Upgrade your plan on Stripe",
  unlimited_access: "Get unlimited access to all AI Estimate features.",
});
